spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8070
eureka:
  instance:
    hostname: eureka-peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer1:8070/eureka/,http://eureka-peer2:8070/eureka/,http://eureka-peer3:8070/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
management:
  endpoints:
    web:
      exposure:
        include: "*"