spring:
  application:
    name: eureka-server

  config:
    import: optional:configserver:http://config-server:8888

server:
  port: 8070

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: false

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://54.166.147.41:8070/eureka/

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

