server:
  port: 8072

spring:
  application:
    name: gateway-server

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
    loadbalancer:
      ribbon:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://54.166.147.41:8080/realms/drake-realm

  zipkin:
    base-url: http://zipkin:9411

eureka:
  instance:
    preferIpAddress: true
    hostname: gateway-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.ecommerce: INFO

