server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://database-1.ct24co2ckluv.us-east-1.rds.amazonaws.com:5432/orderdb
    username: postgres
    password: rdspass1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  cloud:
    config:
      uri: http://config-server:8888

    stream:
      bindings:
        orderCreated-out-0:
          destination: order-events
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092

  zipkin:
    base-url: http://zipkin:9411

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

product:
  service:
    base-url: http://product-service:8081/api

logging:
  level:
    com.ecommerce: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  instance:
    prefer-ip-address: true
    hostname: order-service
  client:
    service-url:
      defaultZone: http://eureka-server:8070/eureka/
    register-with-eureka: true
    fetch-registry: true


