server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://orderdb:5432/orderdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

product:
  service:
    base-url: http://product-service:8081/api

logging:
  level:
    com.ecommerce: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8070/eureka/
    register-with-eureka: true
    fetch-registry: true


# resilience4j:
#   circuitbreaker:
#     instances:
#       productService:
#         registerHealthIndicator: true
#         slidingWindowSize: 5
#         minimumNumberOfCalls: 3
#         waitDurationInOpenState: 10s
#         failureRateThreshold: 50
#         recordExceptions:
#           - org.springframework.web.client.HttpServerErrorException
#           - java.io.IOException
#           - java.util.concurrent.TimeoutException
#           - org.springframework.web.client.ResourceAccessException
    
