spring:
  datasource:
    url: jdbc:postgresql://orderdb:5432/orderdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

product:
  service:
    base-url: http://product-service:8081/api

logging:
  level:
    com.ecommerce: WARN
