server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://productdb:5432/productdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.ecommerce: DEBUG

