spring:
  datasource:
    url: jdbc:postgresql://productdb:5432/productdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: ecomm-redis-7dpadi.serverless.use1.cache.amazonaws.com
      port: 6379
      ssl:
        enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 600000
  cloud:
    stream:
      function:
        definition: consumeOrderCreated
      bindings:
        consumeOrderCreated-in-0:
          destination: order-events
          content-type: application/json
          group: product-service-group
      kafka:
        binder:
          brokers: kafka

logging:
  level:
    com.ecommerce: WARN


           
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException